volumes:
  db_data:
  grafana_data: {}
  prometheus_data: {}
  qdrant_data:
    driver: local

networks:
  rag-network:
    driver: bridge

services:

  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant_service
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - rag-network

  # Estou testando os dockers separadamente (para rodar ele minha memória saiu de 40 GB para 23 GB - e se eu reiniciar?)
  # Confirma como funciona isso do script do meu modelo está no container sozinho
  # trocar os scripts de forma que eles puxem do container, precisa em todos? até testes?

  # no script da api não tem configuração dos modelos...  nem no streamlit...
  # ainda naõ estou usando as configuração dos enviroments que eu criei
  # consigo rodar os comandos do makefile? pros testes só preciso da collection do qdrant

  rag-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: rag-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    networks:
      - rag-network
    restart: unless-stopped

  chat-ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: chat-ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
      - rag-api
    networks:
      - rag-network
    restart: unless-stopped

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - back-tier
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   command: php -S 0.0.0.0:8080 /var/www/html/adminer.php
  #   networks:
  #     - back-tier
  #     - front-tier
  #   depends_on:
  #     - db

  # grafana:
  #   image: grafana/grafana-enterprise
  #   user: "472"
  #   ports:
  #     - "3000:3000"
  #   # volumes:
  #   #   - ./grafana/config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
  #   #   - ./grafana/config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
  #   #   - ./grafana/dashboards:/opt/grafana/dashboards
  #   networks:
  #     - back-tier
  #     - front-tier
  #   restart: always
  #   depends_on:
  #     - db
