volumes:
  db_data:
  grafana_data: {}
  prometheus_data: {}
  qdrant_data:
    driver: local

networks:
  rag-network:
    driver: bridge

services:

  qdrant:
    image: qdrant/qdrant:v1.15.1
    container_name: qdrant_service
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - rag-network

  rag-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: rag-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    networks:
      - rag-network
    restart: unless-stopped

  chat-ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: chat-ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - QDRANT_HOST=qdrant
      - RAG_API_HOST=rag-api
    depends_on:
      - qdrant
      - rag-api
    networks:
      - rag-network
    restart: unless-stopped

  monitoring-dash:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    container_name: monitoring-dash
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - rag-network
    restart: unless-stopped
