name: Lint Code Base
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.23'
      - name: Install dependencies
        run: |
          pip install pylint black
      - name: Run Pylint
        run: |
          pylint **/*.py --exit-zero
      - name: Install Black
        run: pip install black==25.1.0
      - name: Run Black Check
        run: |
          if ls **/*.py 1> /dev/null 2>&1; then
            black --check --line-length=78 **/*.py
          else
            echo "File .py not found. Skip Black step."
          fi
